### ISSUE TITLE
Linear memory import : initial size meaning ?

### ISSUE THREAD

**Issue by BLTSIZE** [sunfishcode/wasm-reference-manual#10]
In the [this section](https://github.com/sunfishcode/wasm-reference-manual/blob/master/WebAssembly.md#import-section) of this great document, it is written that:

_A linear-memory import's minimum length is required to be at most the imported linear memory's minimum length._

Which is perfectly correct according to [this section](https://webassembly.org/docs/modules/#imports) of the WebAssembly official documentation. The initial size of the memory declared in the module must but at least the initial size of the imported memory.

But this raises a question: what if the initial size of the memory declared in the module is less than the initial size of the imported memory?

The following module does compile with [wat2wasm](https://webassembly.github.io/wabt/demo/wat2wasm/):
```

(module
	(memory (import "imports" "memory") 1)
	(func (export "fillMemory")
		(local $count i32)
      	(local $index i32)
		(set_local $count (i32.const 32768))		;; 2 pages of 32 bits words
		(set_local $index (i32.const 0))
		(block
			(loop
				(i32.store (get_local $index) (i32.const 0x01010101))
				(set_local $index (i32.add (get_local $index) (i32.const 4)))
				(set_local $count (i32.sub (get_local $count) (i32.const 1)))
				(br_if 1 (i32.eqz (get_local $count)))
				br 0
			)
		)
	)
)

```
It may be run with this program:
```

var nbPages = 2;
var importObject = {
	imports: {
		memory: new WebAssembly.Memory ({ initial: nbPages })
	}
};
var wasmInstance = new WebAssembly.Instance (wasmModule, importObject);
wasmInstance.exports.fillMemory ();
var i, total = 0, bytes;
bytes = new Uint8Array (importObject.imports.memory.buffer);
for (var i = 0; i < nbPages * 65536; i++)
  total += bytes[i];
console.log (`Read ${total} bytes`);

```
The result printed in the console is "Read 131072 bytes". This means that the code in the module is able to write 2 pages of 32 bits integers in the imported memory, although the initial value is said to be 1 in the module. It would be nice if the WASM Reference Manual explain why.

**Comment by sunfishcode** [comment]
This is why the document uses the term `minimum` rather than `initial`. The size of the memory at runtime may be greater than the `minimum` size, either by being bigger at the time it's imported, or by a `memory.grow`, from within the instance or from within some other instance sharing its memory. Loads and stores succeed if they're within the dynamic size.

**Comment by sunfishcode** [comment]
If there are any follow-up questions, please reopen or file new issues!
