### ISSUE TITLE
Missing 'data mode' docs for data/elements sections? Data size section?

### ISSUE THREAD

**Issue by blitz-research** [sunfishcode/wasm-reference-manual#21]
Hi, 

The docs for data sections seems to be out dated - there's a whole 'data mode' scheme for 'active' and 'passive' data, see:

https://webassembly.github.io/spec/core/binary/modules.html#data-section

The elements section also has a similar setup I believe.

Also missing is docs for section type '12' which I think just contains size of data section.

**Comment by sunfishcode** [comment]
Yes, that's correct. I'm not currently working on adding new features to this document.

**Comment by blitz-research** [comment]
Okay, no problem, a bit of a shame as they're by far the most readable webassembly docs around IMO, but I understand it's a massive job!
