### ISSUE TITLE
Table-of-contents-crx

### ISSUE THREAD

**Issue by synagonism** [sunfishcode/wasm-reference-manual#6]
Table-of-contents-crx[1] is a-Chrome-extension that facilitates the-reading of the-document.
[1] https://chrome.google.com/webstore/detail/table-of-contents-crx/eeknhipceeelbgdbcmchicoaoalfdnhi

**Comment by sunfishcode** [comment]
Does it support [the Web Extensions API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions)?

**Comment by synagonism** [comment]
No, unfortunately was-written for Chrome only!

**Comment by sunfishcode** [comment]
I won't be able to recommend it until it does.
