### ISSUE TITLE
Small inaccuracy about the `body_size` field in the Code section

### ISSUE THREAD

**Issue by tomsmeding** [sunfishcode/wasm-reference-manual#8]
First of all, thanks for this amazing resource!

While working on a toy webassembly parser, I noticed an inconsistency with the official spec in your description of the Code section (`#code-section`). You state that `body_size` describes "the size of `body` in bytes", while in fact it describes the size of `locals` plus the size of `body`, in bytes. This is stated in the [formal specification](https://webassembly.github.io/spec/core/binary/modules.html#code-section):

> 
> The encoding of each code entry consists of
> - the u32 size of the function code in bytes,
> - the actual function code, which in turn consists of
>   - the declaration of locals,
>   - the function body as an expression.

I wasn't sure how you'd want to have this formulated in your document, so I opted to write this issue instead of directly making a PR.

Just wanted to post a heads-up; thanks again for the effort to write this up in an accessible manner!

**Comment by sunfishcode** [comment]
Thanks for the report! I've opened #9 with a fix.

**Comment by tomsmeding** [comment]
The PR looks great! :)
